services:
  - type: web
    name: pesquisa-transporte
    env: python
    # Descomprime o código-fonte do sistema a partir do arquivo tarball gerado.
    # Em seguida instala as dependências Python a partir de requirements.txt.
    buildCommand: |
      tar -xzf sistema_pesquisa_transporte_atualizado.tar.gz
      pip install -r requirements.txt
    # Inicializa o serviço usando gunicorn apontando para a aplicação Flask
    startCommand: "gunicorn --bind 0.0.0.0:$PORT src.main:app"
    healthCheckPath: "/health"
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: pesquisa-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production

databases:
  - name: pesquisa-db
    databaseName: pesquisa_transporte
    user: pesquisa_user
    plan: free

